<!Story>
    Once upon there was a deer that was not killed. it was a big deer.
the last deer on the planet...

<!Prompt>
<!Prompt_Info>
What do you want to name the deer?
deer_name


<!Story_Spec>
<!Escape> deer_name roamed the land and was very bored of life.

<!Story>
Then a hunter came about... looking for game.

<!Prompt>
<!Prompt_Info>
What do you want to name the Man?
man_name

<!Story_Spec>
<!Escape> man_name then happened to see <!Escape> deer_name trotting around through the city.
And then...

<!Prompt>
<!Prompt_Choice>
2
1) the man kills the deer.
kill_deer
2) the man is unable to kill the deer
not_kill_deer