<!Story>
    Once upon there was a deer that was not killed. it was a big deer.
the last deer on the planet...

<!Prompt>
<!Prompt_Info>
What do you want to name the deer?
deer_name


<!Story>
<!Escape> deer_name roamed the land and was very bored of life.
Then a hunter came about... looking for game.

<!Prompt>
<!Prompt_Info>
What do you want to name the Man?
man_name

<!Story>
<!Escape> man_name then happened to see <!Escape> deer_name trotting around through the city.
And then...

<!Prompt>
<!Prompt_Choice>
2
1) <!Escape> man_name kills <!Escape> deer_name
kill_deer
2) <!Escape> man_name is unable to kill <!Escape> deer_name
not_kill_deer